openapi: 3.0.0
info:
  title: Planetwar Api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /map:
    get:
      summary: Query whole map
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Map'
      operationId: get-map
      tags:
        - Gameinformation
components:
  schemas:
    Ships:
      title: Ships
      type: object
      description: Collection of ships
      properties:
        location:
          $ref: '#/components/schemas/Location'
        amount:
          type: string
        owner:
          $ref: '#/components/schemas/Owner'
      required:
        - location
        - amount
        - owner
    Location:
      title: Location
      type: object
      properties:
        X:
          type: integer
          minimum: 0
          description: X coordinate on map
        'Y':
          type: integer
          minimum: 0
          description: Y coordinate on map
      required:
        - X
        - 'Y'
    Tile:
      title: Tile
      type: object
      description: Stores the objects of one map tile
      properties:
        location:
          $ref: '#/components/schemas/Location'
        ships:
          $ref: '#/components/schemas/Ships'
        hasShips:
          type: boolean
          description: Ships is only set if hasShips is true
        planet:
          $ref: '#/components/schemas/Planet'
        hasPlanet:
          type: boolean
          description: Planet is only set if hasPlanet is true
      required:
        - location
        - hasShips
        - hasPlanet
    Planet:
      title: Planet
      type: object
      description: Stores planet information
      properties:
        location:
          $ref: '#/components/schemas/Location'
        owner:
          $ref: '#/components/schemas/Owner'
        production:
          type: integer
          minimum: 0
          exclusiveMinimum: true
          description: Production of ships per round
        skin:
          type: integer
          minimum: 0
          description: The planets skin
      required:
        - location
        - owner
        - production
        - skin
    Owner:
      title: Owner
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The owner uuid
        name:
          type: string
          description: Owner display name
      required:
        - id
        - name
    Map:
      title: Map
      type: array
      description: A collection of tiles that make up the map
      items:
        $ref: '#/components/schemas/Tile'
